### PR TITLE
Add Stadtmobil Stuttgart

### PR DESCRIPTION
**Pull request by hbruch**
This PR adds Stadtmobil Stuttgart.

Besides adding some Stuttgart specific name/propulsion handling, this PR removes the need for provider specific subclasses  by reading the available pricing plans directly from the config.

### CODE REVIEW

**Comment by ThorstenFroehlinghaus** [comment]
one question: the Cantamen IXSI response already contains other Stadtmobil providers (Rhein-Neckar/Karlsruhe). could the x2gbfs check for "stadmobil_*" run into problems if there is no config file available for this provider?

**Comment by hbruch** [comment]
This would fail already one step before, as the config file is loaded before the provider is instantiated:

```
FileNotFoundError: [Errno 2] No such file or directory: 'config/stadtmobil_xyz.json'
```

**Comment by ThorstenFroehlinghaus** [comment]
Ok, so the PR is ok for me.

**Review by ThorstenFroehlinghaus — APPROVED** [review]
Changes are ok.

**Pull request merged**
